<?php

namespace DT\Autolink\Middleware;

use DT\Autolink\Psr\Http\Message\ResponseInterface;
use DT\Autolink\Psr\Http\Message\ServerRequestInterface;
use DT\Autolink\Psr\Http\Server\MiddlewareInterface;
use DT\Autolink\Psr\Http\Server\RequestHandlerInterface;
use function DT\Autolink\route_url;
use function DT\Autolink\redirect;

class LoggedOut implements MiddlewareInterface
{

	/**
	 * If the user is logged in, redirect to the home page.
	 *
	 * @param ServerRequestInterface $request The server request to be processed.
	 * @param RequestHandlerInterface $handler The request handler to forward the request to.
	 *
	 * @return ResponseInterface The response generated by processing the request.
	 */
	public function process( ServerRequestInterface $request, RequestHandlerInterface $handler ): ResponseInterface
	{

		if ( is_user_logged_in() ) {

			return redirect( route_url() );

		}

		return $handler->handle( $request );
	}
}
