name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'

      - name: Add Composer Global to PATH
        run: echo "$(composer global config bin-dir --absolute --quiet)" >> $GITHUB_PATH

      - name: Install Scoper
        run: |
          ./bin/setup-scoper.sh

      - name: Install dependencies
        run: composer install --no-interaction --ignore-platform-reqs

      - name: Test syntax
        run: ./bin/test-for-syntax-errors.sh

      - name: Zip vendor directories
        run: |
          tar -czf vendor.tar.gz vendor
          tar -czf vendor-scoped.tar.gz vendor-scoped

      - name: Upload vendor directory
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor.tar.gz

      - name: Upload vendor-scoped directory
        uses: actions/upload-artifact@v4
        with:
          name: vendor-scoped
          path: vendor-scoped.tar.gz

      - name: Package release
        run: |
          mkdir dt-autolink
          cp -r dt-autolink.php config dist languages resources routes src vendor vendor-scoped composer.json composer.lock composer.scoped.json composer.scoped.lock LICENSE package.json package-lock.json phpcs.xml dt-autolink/
          zip -r dt-autolink.zip dt-autolink

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: dt-autolink.zip
          path: dt-autolink.zip

  tests:
    needs: build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.4', '8.3' ]

    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Add Composer Global to PATH
        run: echo "$(composer global config bin-dir --absolute --quiet)" >> $GITHUB_PATH

      - name: Download vendor directory
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: .

      - name: Download vendor-scoped directory
        uses: actions/download-artifact@v4
        with:
          name: vendor-scoped
          path: .

      - name: Unzip vendor directories
        run: |
          tar -xzf vendor.tar.gz
          tar -xzf vendor-scoped.tar.gz
          export PATH="$HOME/.composer/vendor/bin:$PATH"
          export PATH="$HOME/.composer/vendor-scoped/bin:$PATH"

      - name: Download release
        uses: actions/download-artifact@v4
        with:
          name: dt-autolink.zip
          path: .

      - name: Test phpcs
        run: ./bin/test-phpcs.sh

      - name: Install Subversion
        run: |
          sudo apt-get update
          sudo apt-get install subversion -y

      - name: Install WP Tests
        run: ./bin/install-wp-tests.sh wordpress_test root rootpassword 127.0.0.0 latest
        shell: bash

      - name: PHPunit
        run: |
          vendor/bin/phpunit
