name: CI

on:
    pull_request:
    push:
        branches:
        - main
        - '2.0'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: [ '8.1', '8.2' ]

    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Add Composer Global to PATH
        run: echo "$(composer global config bin-dir --absolute --quiet)" >> $GITHUB_PATH

      - name: Install Scoper
        run: |
          ./setup-scoper.sh

      - name: Install dependencies
        run: composer install --no-interaction --ignore-platform-reqs

      - name: Test syntax
        run: ./tests/test_for_syntax_errors.sh

#      - name: Test phpcs
#        run: ./tests/test_phpcs.sh
